services:
  - type: web
    name: tilinx-web
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r website/requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py website.wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: TilinX_ADMIN_USER
        value: tilinX
      - key: TilinX_DASH_PASSWORD
        value: hw132319
      - key: TilinX_WEB_SECRET
        generateValue: true
      - key: TilinX_WEB_PORT
        value: 8080
      - key: TilinX_BOT_TOKEN
        value: "8602901015:AAF6RWuaurtKU6jPK-rWD856YumQz8cBr40"
      - key: TilinX_ADMIN_ID
        value: "8659405330"
      - key: TilinX_ADMIN_IP_BIND
        value: "0"
      - key: TilinX_BOT_ENABLED
        value: "0"
      - key: PYTHON_VERSION
        value: 3.11.0
