services:
  - type: web
    name: tilinx-web
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r website/requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py website.wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: TilinX_ADMIN_USER
        value: tilinX
      - key: TilinX_DASH_PASSWORD
        value: hw132319
      - key: TilinX_WEB_SECRET
        generateValue: true
      - key: TilinX_WEB_PORT
        value: 8080
      - key: TilinX_BOT_TOKEN
        value: "8602901015:AAENb3MwiIKrSDZGLZ_Jg8v44IaNrvS7MpU"
      - key: TilinX_ADMIN_ID
        value: "8659405330"
      - key: TilinX_ADMIN_IP_BIND
        value: "0"
      - key: TilinX_BOT_ENABLED
        value: "1"
      - key: TilinX_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_ENABLED
        value: "1"
      - key: SUPABASE_URL
        value: "https://zbenluxgoargangohlwv.supabase.co"
      - key: SUPABASE_KEY
        value: "sb_publishable_cyZWspjSknKoCs-rLkhqAA_1Ov9Huqt"
      - key: SUPABASE_DB_HOST
        value: "db.zbenluxgoargangohlwv.supabase.co"
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: SUPABASE_DB_NAME
        value: "postgres"
      - key: SUPABASE_DB_USER
        value: "postgres"
      - key: SUPABASE_DB_PASSWORD
        value: "P2RGF6kJWqtY0oJm"
